# Fedora packages for personal-fedora.
#
# Missing packages will be installed, but existing packages will not be upgraded.

[packages]

coprs = []

rpms = [
    # Core
    "fish",           # Shell
    "neovim",         # Editor

    # Neovim dependencies
    "fzf",            # Fuzzy finder
    "gopls",          # Go language server
    "python3-neovim", # neovim Python client
]

flatpaks = []
